### ISSUE TITLE
Add Kafka batch publisher

### ISSUE THREAD

**Issue by farbodahm** [DataChefHQ/sparkle#14]
Add KafkaBatchPublisher similar to PR #10.

It should publish one batch of dataframe instead of continuesly streaming it. (If it makes sense, instead of a new class, you can rewrite the main Kafka publisher class to accept a flag to whether publish a batch or stream.)

**Comment by wtfzambo** [comment]
hello

**Comment by wtfzambo** [comment]
Agreed with @farbodahm to write 2 separate classes for the time being
