### ISSUE TITLE
Refactor: Sparkle Writers should be initialized inside class

### ISSUE THREAD

**Issue by farbodahm** [DataChefHQ/sparkle#20]
In the current interface for Sparkle, we are passing Writers as `writers: List[Writer]`. it should be refactored to `writers: List[type[Writer]]`, similar to `readers` argument.

~~Regarding type `List[type[Writer]]`, it can be refactored to an Enum; So instead of `List[type[Writer]]`, we accept `List[WriterType]` which `WriterType` is an enum. Same should happen for reader.~~ (Created #24 another issue)

Reason is initiaizing a Writer requires a SparkSession which we decided to let Sparkle create that session; So it means during initializing a Sparkle app, we don't have access to SparkSession yet and Sparkle should be responsible for initializing Readers and Writers.

**Comment by wtfzambo** [comment]
@farbodahm didn't we suggest in our call to instead of passing `writers: List[type[Writer]]`, to use some kind of Enum or TypedDict instead, to hide implementation away from final user and avoid unnecessary imports?

**Comment by farbodahm** [comment]
@wtfzambo I created #24 to address that issue; For now I would prefer to keep it like this and continue developing Damavand to have something working.
